include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  
  language:
    strict-casts: true
    strict-raw-types: true
  
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
    - unnecessary_new
    
    # Design
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - prefer_single_quotes
    - require_trailing_commas
    
    # Pub
    - sort_pub_dependencies